name: CI Frontend

on:
  workflow_call:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-bun
      - run: bun ci
      - run: bun run lint
        working-directory: frontend
      - run: bun run build
        working-directory: frontend
