name: CI Frontend

on:
  workflow_call:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: ./.github/actions/setup-bun
      - run: bun ci
      - run: bun run lint
        working-directory: frontend
      - run: bun run build
        working-directory: frontend
